export type ActivityAction =
  // AUTH
  | 'LOGIN_SUCCESS'
  | 'LOGIN_FAILED'
  | 'LOGOUT'
  | 'REFRESH_TOKEN'
  | 'CHANGE_PASSWORD'
  | 'RESET_PASSWORD_REQUEST'
  | 'RESET_PASSWORD_CONFIRM'
  | 'ENABLE_2FA'
  | 'DISABLE_2FA'
  | 'LOCK_ACCOUNT'
  | 'UNLOCK_ACCOUNT'

  // USER & ROLE / PERMISSION
  | 'CREATE_USER'
  | 'UPDATE_USER_PROFILE'
  | 'UPDATE_USER_STATUS'
  | 'UPDATE_USER_ROLE'
  | 'ASSIGN_ROLE'
  | 'REVOKE_ROLE'
  | 'CREATE_ROLE'
  | 'UPDATE_ROLE'
  | 'DELETE_ROLE'
  | 'CREATE_PERMISSION'
  | 'UPDATE_PERMISSION'
  | 'DELETE_PERMISSION'

  // MASTER DATA: BRICK, WORKSHOP, LINE, DEVICE...
  | 'CREATE_BRICK_TYPE'
  | 'UPDATE_BRICK_TYPE'
  | 'DISABLE_BRICK_TYPE'
  | 'ENABLE_BRICK_TYPE'
  | 'CREATE_WORKSHOP'
  | 'UPDATE_WORKSHOP'
  | 'DISABLE_WORKSHOP'
  | 'ENABLE_WORKSHOP'
  | 'CREATE_PRODUCTION_LINE'
  | 'UPDATE_PRODUCTION_LINE'
  | 'DISABLE_PRODUCTION_LINE'
  | 'ENABLE_PRODUCTION_LINE'
  | 'CREATE_MEASUREMENT_TYPE'
  | 'UPDATE_MEASUREMENT_TYPE'
  | 'DISABLE_MEASUREMENT_TYPE'
  | 'ENABLE_MEASUREMENT_TYPE'
  | 'CREATE_DEVICE'
  | 'UPDATE_DEVICE'
  | 'DISABLE_DEVICE'
  | 'ENABLE_DEVICE'
  | 'CREATE_DEVICE_CLUSTER'
  | 'UPDATE_DEVICE_CLUSTER'
  | 'DISABLE_DEVICE_CLUSTER'
  | 'ENABLE_DEVICE_CLUSTER'

  // PRODUCTION PLAN
  | 'CREATE_PRODUCTION_PLAN'
  | 'UPDATE_PRODUCTION_PLAN'
  | 'APPROVE_PRODUCTION_PLAN'
  | 'REJECT_PRODUCTION_PLAN'
  | 'CANCEL_PRODUCTION_PLAN'
  | 'CLOSE_PRODUCTION_PLAN'
  | 'REOPEN_PRODUCTION_PLAN'
  | 'COPY_PRODUCTION_PLAN'

  // STAGE ASSIGNMENT
  | 'START_STAGE_ASSIGNMENT'
  | 'STOP_STAGE_ASSIGNMENT'
  | 'UPDATE_STAGE_ASSIGNMENT'
  | 'SPLIT_STAGE_ASSIGNMENT'
  | 'MERGE_STAGE_ASSIGNMENT'

  // DAILY PRODUCTION
  | 'SYNC_DAILY_PRODUCTION'
  | 'IMPORT_DAILY_PRODUCTION'
  | 'ADJUST_DAILY_PRODUCTION'
  | 'DELETE_DAILY_PRODUCTION'

  // QUALITY
  | 'INPUT_QUALITY_RECORD'
  | 'UPDATE_QUALITY_RECORD'
  | 'DELETE_QUALITY_RECORD'
  | 'IMPORT_QUALITY_RECORD'

  // IOT & MEASUREMENT
  | 'SYNC_TELEMETRY_BATCH'
  | 'SYNC_MEASUREMENT_CACHE'
  | 'PURGE_MEASUREMENT_CACHE'
  | 'DEVICE_TIMEOUT'
  | 'DEVICE_RECOVERED'
  | 'UPDATE_DEVICE_CONFIG'
  | 'UPDATE_CLUSTER_CONFIG'
  | 'TEST_DEVICE_CONNECTION'
  | 'TEST_MQTT_PUBLISH'

  // SALARY & KPI
  | 'RUN_SALARY_CALCULATION'
  | 'RERUN_SALARY_CALCULATION'
  | 'APPROVE_SALARY'
  | 'REJECT_SALARY'
  | 'ADJUST_SALARY_ITEM'
  | 'LOCK_SALARY_PERIOD'
  | 'UNLOCK_SALARY_PERIOD'
  | 'RUN_KPI_CALCULATION'

  // REPORT & EXPORT
  | 'EXPORT_PRODUCTION_REPORT'
  | 'EXPORT_QUALITY_REPORT'
  | 'EXPORT_SALARY_REPORT'
  | 'EXPORT_DEVICE_LOG'
  | 'EXPORT_PLAN_LIST'
  | 'GENERATE_DASHBOARD_SNAPSHOT'

  // SETTINGS & SYSTEM
  | 'UPDATE_SYSTEM_SETTING'
  | 'RESET_SYSTEM_SETTING'
  | 'BACKUP_DATABASE'
  | 'RESTORE_DATABASE'
  | 'RUN_MIGRATION'
  | 'ROLLBACK_MIGRATION'
  | 'START_BACKGROUND_JOB'
  | 'STOP_BACKGROUND_JOB'

  // TOKEN / API KEY
  | 'GENERATE_API_TOKEN'
  | 'REVOKE_API_TOKEN'

  // FILE / ATTACHMENT
  | 'UPLOAD_ATTACHMENT'
  | 'DELETE_ATTACHMENT'

  // OTHER
  | 'MANUAL_DATA_FIX'
  | 'OTHER_ACTION';
